source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"
use_frameworks!

target "Eventperk" do

# Network
#pod 'Alamofire', '~> 4.2'
#pod 'ReachabilitySwift', '~> 3'
#pod 'Kingfisher', '~> 3.2'
pod 'AWSCognito', '~> 2.5'
pod 'AWSCognitoIdentityProvider', '~> 2.5'
pod 'AWSS3'
pod 'FBSDKCoreKit', '~> 4.20'
pod 'FBSDKLoginKit', '~> 4.20'
pod 'AWSSNS'
pod 'AWSLambda'
pod 'AWSDynamoDB'
pod 'GoogleSignIn'

# Push
#pod 'OneSignal', '~> 2.3'

# Database
pod 'RealmSwift', '~> 2.5'
#pod 'SwiftyJSON', '~> 3.1'
#pod 'SwiftyUserDefaults', '~> 3.0'
#pod 'KeychainSwift', '~> 7.0'
#pod 'AEXML', '~> 4.0'

# Analytics
#pod 'Fabric'
#pod 'Crashlytics'
#pod 'Firebase/Core'
#pod 'Firebase/Messaging'

# UI
#pod 'RESideMenu', '~> 4.0'
#pod 'NVActivityIndicatorView', '~> 3.2'
#pod 'DynamicBlurView', '~> 1.3'

pod 'SnapKit', '~> 3.1'
pod 'LKAlertController', '~> 1.12'
pod 'ActionSheetPicker-3.0', '~> 2.2'
pod 'APESuperHUD', '~> 1.1'
pod 'AASegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'HCSStarRatingView', '~> 1.5'
pod 'YIPopupTextView'
pod 'OpalImagePicker'
pod 'CountryPicker', '~> 1.3'
pod 'BSImagePicker', '~> 2.4'

# Camera
#pod 'CardIO'

# Digit Mobile Verification
#pod 'Fabric'
#pod 'Digits'
#pod 'TwitterCore'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

