//
//  UserProfile.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.17
//

import Foundation
import UIKit
import AWSDynamoDB

class UserProfile: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _aboutMe: String?
    var _birthDate: String?
    var _createdDate: String?
    var _createdTime: String?
    var _currentSignInAt: String?
    var _currentSignInIp: String?
    var _deviceType: String?
    var _email: String?
    var _encryptedPassword: String?
    var _firstName: String?
    var _gender: String?
    var _language: String?
    var _lastName: String?
    var _lastSignInAt: String?
    var _lastSignInIp: String?
    var _locale: String?
    var _logInStatus: String?
    var _phoneNumber: NSNumber?
    var _responseRate: String?
    var _signInCount: String?
    var _userPhoto: [String]?
    
    class func dynamoDBTableName() -> String {

        return "eventperkios-mobilehub-1122713487-userProfile"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_aboutMe" : "aboutMe",
               "_birthDate" : "birthDate",
               "_createdDate" : "createdDate",
               "_createdTime" : "createdTime",
               "_currentSignInAt" : "currentSignInAt",
               "_currentSignInIp" : "currentSignInIp",
               "_deviceType" : "deviceType",
               "_email" : "email",
               "_encryptedPassword" : "encryptedPassword",
               "_firstName" : "firstName",
               "_gender" : "gender",
               "_language" : "language",
               "_lastName" : "lastName",
               "_lastSignInAt" : "lastSignInAt",
               "_lastSignInIp" : "lastSignInIp",
               "_locale" : "locale",
               "_logInStatus" : "logInStatus",
               "_phoneNumber" : "phoneNumber",
               "_responseRate" : "responseRate",
               "_signInCount" : "signInCount",
               "_userPhoto" : "userPhoto",
        ]
    }
}
