//
//  UserProfileTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.17
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class UserProfileTable: NSObject, Table {
    
    var tableName: String
    var partitionKeyName: String
    var partitionKeyType: String
    var sortKeyName: String?
    var sortKeyType: String?
    var model: AWSDynamoDBObjectModel
    var indexes: [Index]
    var orderedAttributeKeys: [String] {
        return produceOrderedAttributeKeys(model)
    }
    var tableDisplayName: String {

        return "userProfile"
    }
    
    override init() {

        model = UserProfile()
        
        tableName = model.classForCoder.dynamoDBTableName()
        partitionKeyName = model.classForCoder.hashKeyAttribute()
        partitionKeyType = "String"
        indexes = [

            UserProfileIndexKey(),
        ]
        if let sortKeyNamePossible = model.classForCoder.rangeKeyAttribute?() {
            sortKeyName = sortKeyNamePossible
        }
        super.init()
    }
    
    /**
     * Converts the attribute name from data object format to table format.
     *
     * - parameter dataObjectAttributeName: data object attribute name
     * - returns: table attribute name
     */

    func tableAttributeName(_ dataObjectAttributeName: String) -> String {
        return UserProfile.jsonKeyPathsByPropertyKey()[dataObjectAttributeName] as! String
    }
    
    func getItemDescription() -> String {
        let hashKeyValue = AWSIdentityManager.default().identityId!
        return "Find Item with userId = \(hashKeyValue)."
    }
    
    func getItemWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBObjectModel?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        objectMapper.load(UserProfile.self, hashKey: AWSIdentityManager.default().identityId!, rangeKey: nil) { (response: AWSDynamoDBObjectModel?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as NSError?)
            })
        }
    }
    
    func scanDescription() -> String {
        return "Show all items in the table."
    }
    
    func scanWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.limit = 5

        objectMapper.scan(UserProfile.self, expression: scanExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as NSError?)
            })
        }
    }
    
    func scanWithFilterDescription() -> String {
        let scanFilterValue = "demo-aboutMe-500000"
        return "Find all items with aboutMe < \(scanFilterValue)."
    }
    
    func scanWithFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let scanExpression = AWSDynamoDBScanExpression()
        
        scanExpression.filterExpression = "#aboutMe < :aboutMe"
        scanExpression.expressionAttributeNames = ["#aboutMe": "aboutMe" ,]
        scanExpression.expressionAttributeValues = [":aboutMe": "demo-aboutMe-500000" ,]

        objectMapper.scan(UserProfile.self, expression: scanExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        }
    }
    
    func insertSampleDataWithCompletionHandler(_ completionHandler: @escaping (_ errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        var errors: [NSError] = []
        let group: DispatchGroup = DispatchGroup()
        let numberOfObjects = 20
        

        let itemForGet: UserProfile! = UserProfile()
        
        itemForGet._userId = AWSIdentityManager.default().identityId!
        itemForGet._aboutMe = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("aboutMe")
        itemForGet._birthDate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("birthDate")
        itemForGet._createdDate = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._createdTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._currentSignInAt = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("currentSignInAt")
        itemForGet._currentSignInIp = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("currentSignInIp")
        itemForGet._deviceType = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("deviceType")
        itemForGet._email = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("email")
        itemForGet._encryptedPassword = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("encryptedPassword")
        itemForGet._firstName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("firstName")
        itemForGet._gender = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("gender")
        itemForGet._language = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("language")
        itemForGet._lastName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastName")
        itemForGet._lastSignInAt = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastSignInAt")
        itemForGet._lastSignInIp = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastSignInIp")
        itemForGet._locale = NoSQLSampleDataGenerator.randomSampleMap()
        itemForGet._logInStatus = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("logInStatus")
        itemForGet._phoneNumber = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._responseRate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("responseRate")
        itemForGet._signInCount = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("signInCount")
        itemForGet._userPhoto = NoSQLSampleDataGenerator.randomSampleStringArray()
        
        
        group.enter()
        

        objectMapper.save(itemForGet, completionHandler: {(error: Error?) -> Void in
            if let error = error as? NSError {
                DispatchQueue.main.async(execute: {
                    errors.append(error)
                })
            }
            group.leave()
        })
        
        for _ in 1..<numberOfObjects {

            let item: UserProfile = UserProfile()
            item._userId = AWSIdentityManager.default().identityId!
            item._aboutMe = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("aboutMe")
            item._birthDate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("birthDate")
            item._createdDate = NoSQLSampleDataGenerator.randomSampleNumber()
            item._createdTime = NoSQLSampleDataGenerator.randomSampleNumber()
            item._currentSignInAt = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("currentSignInAt")
            item._currentSignInIp = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("currentSignInIp")
            item._deviceType = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("deviceType")
            item._email = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("email")
            item._encryptedPassword = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("encryptedPassword")
            item._firstName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("firstName")
            item._gender = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("gender")
            item._language = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("language")
            item._lastName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastName")
            item._lastSignInAt = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastSignInAt")
            item._lastSignInIp = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastSignInIp")
            item._locale = NoSQLSampleDataGenerator.randomSampleMap()
            item._logInStatus = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("logInStatus")
            item._phoneNumber = NoSQLSampleDataGenerator.randomSampleNumber()
            item._responseRate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("responseRate")
            item._signInCount = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("signInCount")
            item._userPhoto = NoSQLSampleDataGenerator.randomSampleStringArray()
            
            group.enter()
            
            objectMapper.save(item, completionHandler: {(error: Error?) -> Void in
                if error != nil {
                    DispatchQueue.main.async(execute: {
                        errors.append(error! as NSError)
                    })
                }
                group.leave()
            })
        }
        
        group.notify(queue: DispatchQueue.main, execute: {
            if errors.count > 0 {
                completionHandler(errors)
            }
            else {
                completionHandler(nil)
            }
        })
    }
    
    func removeSampleDataWithCompletionHandler(_ completionHandler: @escaping ([NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId"]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.default().identityId!,]

        objectMapper.query(UserProfile.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            if let error = error as? NSError {
                DispatchQueue.main.async(execute: {
                    completionHandler([error]);
                    })
            } else {
                var errors: [NSError] = []
                let group: DispatchGroup = DispatchGroup()
                for item in response!.items {
                    group.enter()
                    objectMapper.remove(item, completionHandler: {(error: Error?) in
                        if let error = error as? NSError {
                            DispatchQueue.main.async(execute: {
                                errors.append(error)
                            })
                        }
                        group.leave()
                    })
                }
                group.notify(queue: DispatchQueue.main, execute: {
                    if errors.count > 0 {
                        completionHandler(errors)
                    }
                    else {
                        completionHandler(nil)
                    }
                })
            }
        }
    }
    
    func updateItem(_ item: AWSDynamoDBObjectModel, completionHandler: @escaping (_ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        

        let itemToUpdate: UserProfile = item as! UserProfile
        
        itemToUpdate._aboutMe = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("aboutMe")
        itemToUpdate._birthDate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("birthDate")
        itemToUpdate._createdDate = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._createdTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._currentSignInAt = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("currentSignInAt")
        itemToUpdate._currentSignInIp = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("currentSignInIp")
        itemToUpdate._deviceType = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("deviceType")
        itemToUpdate._email = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("email")
        itemToUpdate._encryptedPassword = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("encryptedPassword")
        itemToUpdate._firstName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("firstName")
        itemToUpdate._gender = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("gender")
        itemToUpdate._language = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("language")
        itemToUpdate._lastName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastName")
        itemToUpdate._lastSignInAt = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastSignInAt")
        itemToUpdate._lastSignInIp = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("lastSignInIp")
        itemToUpdate._locale = NoSQLSampleDataGenerator.randomSampleMap()
        itemToUpdate._logInStatus = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("logInStatus")
        itemToUpdate._phoneNumber = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._responseRate = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("responseRate")
        itemToUpdate._signInCount = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("signInCount")
        itemToUpdate._userPhoto = NoSQLSampleDataGenerator.randomSampleStringArray()
        
        objectMapper.save(itemToUpdate, completionHandler: {(error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(error as? NSError)
            })
        })
    }
    
    func removeItem(_ item: AWSDynamoDBObjectModel, completionHandler: @escaping (_ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        
        objectMapper.remove(item, completionHandler: {(error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(error as? NSError)
            })
        })
    }
}

class UserProfileIndexKey: NSObject, Index {
    
    var indexName: String? {

        return "indexKey"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
            QueryWithPartitionKeyAndSortKey,
            QueryWithPartitionKeyAndSortKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        let partitionKeyValue = AWSIdentityManager.default().identityId!
        return "Find all items with userId = \(partitionKeyValue)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "indexKey"
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId",]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.default().identityId!,]

        objectMapper.query(UserProfile.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        }
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        let partitionKeyValue = AWSIdentityManager.default().identityId!
        let filterAttributeValue = "demo-aboutMe-500000"
        return "Find all items with userId = \(partitionKeyValue) and aboutMe > \(filterAttributeValue)."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "indexKey"
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.filterExpression = "#aboutMe > :aboutMe"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#aboutMe": "aboutMe",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.default().identityId!,
            ":aboutMe": "demo-aboutMe-500000",
        ]
        

        objectMapper.query(UserProfile.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        })
    }
    
    func queryWithPartitionKeyAndSortKeyDescription() -> String {
        let partitionKeyValue = AWSIdentityManager.default().identityId!
        let sortKeyValue = 1111500000
        return "Find all items with userId = \(partitionKeyValue) and createdDate < \(sortKeyValue)."
    }
    
    func queryWithPartitionKeyAndSortKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "indexKey"
        queryExpression.keyConditionExpression = "#userId = :userId AND #createdDate < :createdDate"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#createdDate": "createdDate",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.default().identityId!,
            ":createdDate": 1111500000,
        ]
        

        objectMapper.query(UserProfile.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: Error?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        })
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterDescription() -> String {
        let partitionKeyValue = AWSIdentityManager.default().identityId!
        let sortKeyValue = 1111500000
        let filterValue = "demo-aboutMe-500000"
        return "Find all items with userId = \(partitionKeyValue), createdDate < \(sortKeyValue), and aboutMe > \(filterValue)."
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "indexKey"
        queryExpression.keyConditionExpression = "#userId = :userId AND #createdDate < :createdDate"
        queryExpression.filterExpression = "#aboutMe > :aboutMe"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#createdDate": "createdDate",
            "#aboutMe": "aboutMe",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.default().identityId!,
            ":createdDate": 1111500000,
            ":aboutMe": "demo-aboutMe-500000",
        ]
        

        objectMapper.query(UserProfile.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        })
    }
}
