//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "ap-northeast-1_0ASbj8nnx"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "73a7mr1foejtaqpq5b1t81e72f"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .APNortheast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "s5sq618t86n4c88284o10ukg8qlti0gsmptms2nodqjtu38jk7p"
